-- SQL ifadelerinizi buraya yazınız.

-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.ogrenci
(
    id smallint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 ),
    ad character varying(20) NOT NULL,
    soyad character varying(20) NOT NULL,
    dtarih date NOT NULL,
    cinsiyet character varying NOT NULL,
    sinif character varying NOT NULL,
    puan bigint NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.islem
(
    id smallint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 ),
    ogrenci_id smallint NOT NULL,
    kitap_id smallint NOT NULL,
    atarih date NOT NULL,
    vtarih date NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.kitap
(
    id smallint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 ),
    ad character varying NOT NULL,
    sayfasayisi character varying NOT NULL,
    puan bigint NOT NULL,
    yazar_id smallint NOT NULL,
    tur_id smallint NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.yazar
(
    id smallint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 ),
    ad character varying NOT NULL,
    soyad character varying NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tur
(
    id smallint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 ),
    ad character varying NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.islem
    ADD FOREIGN KEY (ogrenci_id)
    REFERENCES public.ogrenci (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.islem
    ADD FOREIGN KEY (kitap_id)
    REFERENCES public.kitap (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.kitap
    ADD FOREIGN KEY (yazar_id)
    REFERENCES public.yazar (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.kitap
    ADD FOREIGN KEY (tur_id)
    REFERENCES public.tur (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;